name: Update Guild Data

on:
  schedule:
    - cron: "0 5 * * *"

  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: node scripts/update-guild-data.js

      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          git add data/guild/guild-members-raw-data.json
          git add data/guild/guild-members-processed-data.json

          git commit -m "Update guild data" || echo "No changes"

          git push
